-- =============================================================================
-- 051_backup_and_restore.sql
--
-- Taking the whole book out of Supabase, and putting it back into a new
-- project.
--
-- WHY. The books exist in exactly one place. The project is on the free plan,
-- which has no daily backup anybody can restore from, and a free project pauses
-- when it is left alone. Losing the account, or the project, currently means
-- losing every reading, slip, payment and dip since the pump joined the app.
-- The Excel export is a REPORT - a month at a time, shaped for reading, and it
-- cannot be put back. This is the other thing: everything, in one file, shaped
-- to be reloaded.
--
-- TWO FUNCTIONS, AND THEY ARE NOT PEERS.
--
--   export_everything()   the owner runs it from the app, whenever he likes.
--   restore_everything()  nobody runs from the app, ever. It is reachable only
--                         with the service-role key, from the script in
--                         scripts/restore-backup.mjs, and it refuses a target
--                         that already has trading data in it.
--
-- WHAT IS NOT IN THE BACKUP, both deliberate:
--
--   * activity_log ROWS. The owner's call, and it is the right one: the trail
--     is for answering "what happened last week", it is by far the largest
--     table, and it is the one thing nothing else depends on. The TABLE and its
--     trigger come from migration 035 like everything else, so a restored
--     project starts writing new lines from its first save.
--   * profiles ROWS, because a profile is half of a login and the other half
--     lives in auth.users, which is Supabase's, not ours. Passwords are hashes
--     no API hands out. So logins are recreated by hand in the new project and
--     the script maps the old profile ids onto the new ones by name - see
--     `p_profile_map` below. Names ARE exported, so you know which logins to
--     make and what they were called.
--
-- WHAT A RESTORE HAS TO SURVIVE, which is the whole reason this is a database
-- function and not a loop in JavaScript. Inserting these rows through the
-- normal path would re-run fifty migrations' worth of triggers on data that has
-- already been through them once:
--
--   * a credit slip AUTO-POSTS its own ledger entry, so restoring both would
--     double every credit customer's balance;
--   * tank and lubricant stock are RECALCULATED per row, dozens of times, from
--     a partly-loaded table;
--   * readings may not overlap, a day must balance, the safe may never go
--     below zero at any point in the chain - all true of the finished data and
--     not necessarily true half way through loading it in table order.
--
-- So the restore disables user triggers for the length of one transaction,
-- loads in dependency order, turns them back on, and then recomputes the two
-- derived stock figures itself. Everything else in the schema is either stored
-- or generated by Postgres and needs nothing.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- The table list, in dependency order, in ONE place.
--
-- Both functions read it. A future table added to the schema and forgotten here
-- would be silently left out of every backup taken afterwards, which is the
-- worst failure this file could have - so `backup_tables_missing()` below names
-- anything in public that neither list mentions, and the export calls it and
-- puts the answer in the file's own header rather than trusting a comment.
-- ---------------------------------------------------------------------------
create or replace function public.backup_table_order()
returns text[]
language sql
immutable
as $$
  select array[
    'tanks', 'nozzles', 'customers', 'lubricants', 'bank_accounts',
    'fuel_prices', 'company_assets', 'expenses', 'treasury_entries',
    'nozzle_readings', 'fuel_purchases', 'lubricant_purchases', 'stock_checks',
    'lubricant_sales', 'credit_sales', 'ledger_entries', 'bank_transactions'
  ]::text[];
$$;

comment on function public.backup_table_order() is
  'Every table the backup carries, parents before children. Load order for a restore.';

-- ---------------------------------------------------------------------------
-- The tables a FRESH project is not empty in.
--
-- Three migrations put rows into a new database before anybody has typed
-- anything: 004/013 the two tanks and six nozzles, 012 their starting meter
-- readings, and 045 the owner's real Tajori sheet - thirty-six treasury
-- movements up to 21 Aug 2026. So "restore only into an empty project" cannot
-- mean "every table has nothing in it"; it means nothing beyond these.
--
-- They are cleared and replaced wholesale by what the file holds, which is
-- correct rather than merely convenient: the file's own copy of these rows came
-- from a database that was seeded exactly the same way, so it contains the
-- seed plus everything that happened after it.
--
-- This list was written by RUNNING the restore into a freshly migrated
-- database, not by reading the migrations - which is how the treasury seed was
-- found. See docs/CHANGELOG.md.
-- ---------------------------------------------------------------------------
create or replace function public.backup_seeded_tables()
returns text[]
language sql
immutable
as $$
  -- Children first: this is also the delete order.
  select array['nozzles', 'tanks', 'treasury_entries']::text[];
$$;

comment on function public.backup_seeded_tables() is
  'Tables the migrations themselves put rows in. A restore replaces these rather than refusing.';

-- Tables that exist and are in neither the backup list nor the known-excluded
-- list. Should always be empty; if it is not, the export says so in the file.
create or replace function public.backup_tables_missing()
returns text[]
language sql
stable
set search_path = public
as $$
  select coalesce(array_agg(c.relname order by c.relname), array[]::text[])
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and c.relkind = 'r'
     and not (c.relname = any (public.backup_table_order()))
     -- Excluded on purpose, both explained in the header.
     and not (c.relname = any (array['activity_log', 'profiles']));
$$;

comment on function public.backup_tables_missing() is
  'Public tables in neither the backup list nor the deliberate exclusions. Should be empty.';

-- ---------------------------------------------------------------------------
-- The backup.
--
-- One jsonb document: a header saying what it is and what it was taken from,
-- then every row of every table. Generated columns are exported too - they are
-- read by a human checking the file, and the restore drops them on the way in.
--
-- Owner only. It is the entire book in one response, which is exactly the thing
-- a staff login must never be able to ask for.
-- ---------------------------------------------------------------------------
create or replace function public.export_everything()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_table   text;
  v_rows    jsonb;
  v_tables  jsonb := '{}'::jsonb;
  v_counts  jsonb := '{}'::jsonb;
  v_n       bigint;
begin
  if not public.is_super_admin() then
    raise exception 'Only the owner may take a backup' using errcode = '42501';
  end if;

  foreach v_table in array public.backup_table_order() loop
    execute format(
      'select coalesce(jsonb_agg(to_jsonb(t) order by t), ''[]''::jsonb) from public.%I t',
      v_table
    ) into v_rows;

    v_tables := v_tables || jsonb_build_object(v_table, v_rows);
    v_counts := v_counts || jsonb_build_object(v_table, jsonb_array_length(v_rows));
  end loop;

  -- The names behind created_by, so a restore can map them onto the logins of
  -- the new project, and so the file says who was working here. No email, no
  -- password, nothing from auth.users - there is nothing secret in this.
  select coalesce(jsonb_agg(jsonb_build_object(
           'id', p.id, 'full_name', p.full_name, 'role', p.role
         ) order by p.full_name), '[]'::jsonb)
    into v_rows
    from public.profiles p;

  select count(*) into v_n from public.activity_log;

  return jsonb_build_object(
    'schema_version', 1,
    'generated_at',   now(),
    'pump_date',      public.pump_today(),
    'migration',      '051',
    'profiles',       v_rows,
    'excluded',       jsonb_build_object(
                        'activity_log', jsonb_build_object(
                          'rows_not_exported', v_n,
                          'why', 'The audit trail is not restored. The table and its trigger '
                                 'come from migration 035, so a restored project writes new lines.'),
                        'profiles', jsonb_build_object(
                          'why', 'A profile is half of a login; the other half is in auth.users. '
                                 'Names and roles are listed above so the logins can be remade.')
                      ),
    'unlisted_tables', to_jsonb(public.backup_tables_missing()),
    'counts',          v_counts,
    'tables',          v_tables
  );
end;
$$;

comment on function public.export_everything() is
  'The whole book as one jsonb document, for backup. Owner only. Excludes activity_log rows and profiles.';

-- ---------------------------------------------------------------------------
-- Repointing a row at the login that stands for its old author.
--
-- Every created_by in the schema is nullable, which is what makes this safe: a
-- name with no match in the new project leaves the entry standing with nobody
-- against it, rather than refusing the whole restore over a member of staff who
-- has since left.
-- ---------------------------------------------------------------------------
create or replace function public.restore_remap_actor(p_row jsonb, p_map jsonb)
returns jsonb
language sql
immutable
as $$
  select case
           when not (p_row ? 'created_by')      then p_row
           when p_row ->> 'created_by' is null  then p_row
           else jsonb_set(
                  p_row, '{created_by}',
                  coalesce(p_map -> (p_row ->> 'created_by'), 'null'::jsonb)
                )
         end;
$$;

comment on function public.restore_remap_actor(jsonb, jsonb) is
  'Rewrites a row''s created_by through an old-id -> new-id map; unmatched becomes null.';

-- ---------------------------------------------------------------------------
-- The restore.
--
-- NOT REACHABLE FROM THE APP. Execute is granted to service_role alone, and the
-- first thing it does is check the role it is running as - so no signed-in
-- browser session, owner included, can call it even by hitting the endpoint
-- directly. It is a disaster-recovery tool run from a laptop with the service
-- key, once, into an empty project.
--
-- It refuses a target that already holds trading data. Merging two books is not
-- a thing anyone should ask a script to attempt, and "restore over the top of
-- what is there" is how a bad backup destroys a good database. What the
-- migrations themselves seed is the one exception - see
-- backup_seeded_tables().
-- ---------------------------------------------------------------------------
create or replace function public.restore_everything(
  p_payload     jsonb,
  p_profile_map jsonb default '{}'::jsonb,
  p_confirm     text  default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_table    text;
  v_cols     text;
  v_rows     jsonb;
  v_n        bigint;
  v_loaded   jsonb := '{}'::jsonb;
  v_identity boolean;
  v_column   text;
  v_sequence text;
  v_occupied text[] := array[]::text[];
  v_version  int;
begin
  -- Who may run this. current_user is the role PostgREST switched into, so a
  -- request made with the anon or a user's token cannot reach the body.
  if current_user not in ('service_role', 'postgres', 'supabase_admin') then
    raise exception
      'A restore runs from the recovery script with the service-role key, not from the app.'
      using errcode = '42501';
  end if;

  if coalesce(p_confirm, '') <> 'RESTORE' then
    raise exception 'Pass RESTORE as the confirmation to load a backup.' using errcode = '23514';
  end if;

  v_version := (p_payload ->> 'schema_version')::int;
  if v_version is distinct from 1 then
    raise exception
      'This file says schema_version %, and this database can only load version 1.',
      coalesce(v_version::text, 'nothing')
      using errcode = '23514';
  end if;

  if p_payload -> 'tables' is null then
    raise exception 'That file has no tables in it.' using errcode = '23514';
  end if;

  -- Is there anything here already? What the migrations seed does not count -
  -- see backup_seeded_tables().
  foreach v_table in array public.backup_table_order() loop
    if v_table = any (public.backup_seeded_tables()) then
      continue;
    end if;
    execute format('select count(*) from public.%I', v_table) into v_n;
    if v_n > 0 then
      v_occupied := v_occupied || format('%s (%s)', v_table, v_n);
    end if;
  end loop;

  if array_length(v_occupied, 1) > 0 then
    raise exception
      'This database already has data in it: %. A restore only ever loads into an empty '
      'project - it does not merge, and it does not overwrite.',
      array_to_string(v_occupied, ', ')
      using errcode = '23505';
  end if;

  -- Off, for the length of this transaction. Everything in the file has already
  -- been through these triggers once; running them again on a half-loaded table
  -- would double the ledger and recompute stock from data that is not all there
  -- yet. See the header.
  foreach v_table in array public.backup_table_order() loop
    execute format('alter table public.%I disable trigger user', v_table);
  end loop;

  -- What the migrations seeded makes way for the file's own copy of it. The
  -- list is in delete order, children first.
  foreach v_table in array public.backup_seeded_tables() loop
    execute format('delete from public.%I', v_table);
  end loop;

  foreach v_table in array public.backup_table_order() loop
    v_rows := coalesce(p_payload -> 'tables' -> v_table, '[]'::jsonb);

    if jsonb_typeof(v_rows) <> 'array' then
      raise exception 'The % section of that file is not a list of rows.', v_table
        using errcode = '23514';
    end if;

    select coalesce(jsonb_agg(public.restore_remap_actor(r, p_profile_map)), '[]'::jsonb)
      into v_rows
      from jsonb_array_elements(v_rows) r;

    -- Generated columns are computed by Postgres and may not be written to.
    -- IDENTITY columns are a different case and are written: treasury_entries
    -- keeps its running order as (entry_date, seq), so a seq handed out afresh
    -- on the way in would reorder two movements made on the same day - and the
    -- treasury page reads that order as the sequence of the day. It takes
    -- `overriding system value` to write one, and the sequence is moved past
    -- the restored values afterwards.
    select string_agg(quote_ident(c.column_name), ', ' order by c.ordinal_position),
           bool_or(c.is_identity = 'YES')
      into v_cols, v_identity
      from information_schema.columns c
     where c.table_schema = 'public'
       and c.table_name = v_table
       and c.is_generated = 'NEVER';

    execute format(
      'insert into public.%I (%s) %s select %s from jsonb_populate_recordset(null::public.%I, $1)',
      v_table, v_cols,
      case when v_identity then 'overriding system value' else '' end,
      v_cols, v_table
    ) using v_rows;

    get diagnostics v_n = row_count;
    v_loaded := v_loaded || jsonb_build_object(v_table, v_n);
  end loop;

  foreach v_table in array public.backup_table_order() loop
    execute format('alter table public.%I enable trigger user', v_table);
  end loop;

  -- An identity column was written with its old values, so the sequence behind
  -- it is still sitting at 1 and the next insert would collide with a restored
  -- row. Move it past everything that landed.
  for v_table, v_column in
    select c.table_name, c.column_name
      from information_schema.columns c
     where c.table_schema = 'public'
       and c.table_name = any (public.backup_table_order())
       and c.is_identity = 'YES'
  loop
    v_sequence := pg_get_serial_sequence(format('public.%I', v_table), v_column);
    if v_sequence is not null then
      execute format(
        'select setval(%L, coalesce((select max(%I) from public.%I), 0) + 1, false)',
        v_sequence, v_column, v_table
      );
    end if;
  end loop;

  -- The two figures the schema keeps as a running total rather than deriving on
  -- read. Everything else is either stored or generated.
  perform public.recalc_tank_stock(t.id) from public.tanks t;
  perform public.recalc_lubricant_stock(l.id) from public.lubricants l;

  return jsonb_build_object(
    'restored_from', p_payload ->> 'generated_at',
    'loaded',        v_loaded,
    'unmapped_authors', (
      select count(*) from jsonb_array_elements(coalesce(p_payload -> 'profiles', '[]'::jsonb)) p
       where p_profile_map -> (p ->> 'id') is null
    )
  );
end;
$$;

comment on function public.restore_everything(jsonb, jsonb, text) is
  'Loads a backup into an EMPTY project: triggers off, dependency order, '
  'created_by remapped onto this project''s logins, stock recomputed. '
  'service_role only - never callable from the app.';

revoke execute on function public.export_everything()                      from public, anon;
revoke execute on function public.restore_everything(jsonb, jsonb, text)   from public, anon, authenticated;
revoke execute on function public.restore_remap_actor(jsonb, jsonb)        from public, anon;
revoke execute on function public.backup_tables_missing()                  from public, anon;
revoke execute on function public.backup_seeded_tables()                  from public, anon;
grant  execute on function public.export_everything()                      to authenticated;
grant  execute on function public.restore_everything(jsonb, jsonb, text)   to service_role;
